# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BLEND 360 Optimization Center of Excellence
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
#  name   : "Optimization CoE @ BLEND 360"
#  avatar : "/assets/images/coe-logo-v1.0.png"
  bio : "The optimization center of excellence @ BLEND 360 leads our organization in developing perspective analytics, mathematical programming, and optimization solutions for our clients in a wide variety of industries. We are also committed to share our experience and innovative solutions with the larger optimization community because we believe knowledge sharing is an integral part of innovation."
  links:
    - label: "BLEND 360"
      icon: "fas fa-fw fa-link"
      url: "https://www.blend360.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/blend360"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/orgs/BLEND360/teams/optimizationcoe/repositories"

footer:
  links:
    - label: "BLEND 360"
      icon: "fas fa-fw fa-link"
      url: "https://www.blend360.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/blend360"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/orgs/BLEND360/teams/optimizationcoe/repositories"

collections:
    team:
      output: true
      permalink: team/:title/

defaults:
  # _team
  - scope:
      path: ""
      type: team
    values:
      layout: single #author
      author_profile: false
      permalink: /team/:slug
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
